### ISSUE TITLE
Cloud Build Failed: Pip Pytorch Killed

### ISSUE THREAD

**Issue by achen353** [livingbio/fewshot-vid2vid#1]
Cloud Build Log: https://console.cloud.google.com/cloud-build/builds/1a1b1053-0d9d-459c-817d-4d26778a6c44?authuser=1&project=living-bio

目前 pytorch 的安裝是在安裝完 requirements.txt 後另外依照 cuda version 安裝
https://github.com/livingbio/fewshot-vid2vid/blob/d82c87aced50afd44fd162491ba5b59056b74034/scripts/install.sh#L34
（requirements.txt 裡的 package 也會安裝 pytorch dependency，但是無法選擇 pytorch cuda version，會自動安裝對應 cuda 10.2 的 pytorch，所以設定成 requirements.txt 之後再重新安裝 pytorch）

在 cloud build 的時候會 processed killed，導致後面的編譯會 cuda 報錯
<img width="865" alt="Screen Shot 2021-11-03 at 11 11 09 AM" src="https://user-images.githubusercontent.com/21190239/140087699-7fda358a-02cd-4744-b71c-ed12973d31dc.png">

**Comment by lucemia** [comment]
Processed Killed 可能是 OOM  (Out of Memory) 了
試試看調整 Cloud Build Machine Type 
https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#machinetype

**Comment by achen353** [comment]
> Processed Killed 可能是 OOM (Out of Memory) 了 試試看調整 Cloud Build Machine Type https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#machinetype



剛剛調了這個不過好像無效
https://github.com/livingbio/fewshot-vid2vid/blob/a52a85b8493b705dd3c9eb19ed51b7c22b2794b4/app.yaml#L8
和調整 machine type 有什麼差別嗎

**Comment by lucemia** [comment]
> （requirements.txt 裡的 package 也會安裝 pytorch dependency，但是無法選擇 pytorch cuda version，會自動安裝對應 cuda 10.2 的 pytorch，所以設定成 requirements.txt 之後再重新安裝 pytorch）

無法選擇 pytorch 的意思指的是什麼呢? 
requirements.txt 裡面是可以指定 version 的
https://github.com/livingbio/gstudio/blob/master/requirements/test.txt

**Comment by achen353** [comment]
> > （requirements.txt 裡的 package 也會安裝 pytorch dependency，但是無法選擇 pytorch cuda version，會自動安裝對應 cuda 10.2 的 pytorch，所以設定成 requirements.txt 之後再重新安裝 pytorch）
> 
> 無法選擇 pytorch 的意思指的是什麼呢? requirements.txt 裡面是可以指定 version 的 https://github.com/livingbio/gstudio/blob/master/requirements/test.txt

requirments.txt 裡面其實沒有 torch, torchvision, torchaudio，是裡面某個 package 的 dependency 自動安裝 torch 的，不確定為什麼 pip 沒有自動抓對應系統 cuda 的 torch 安裝 

我嘗試修改 requirements.txt 看看

**Comment by lucemia** [comment]
這裡提到可能是硬碟不夠大
https://stackoverflow.com/questions/62669720/process-got-killed-when-building-docker-image-on-gcp

預設是 100gb
https://cloud.google.com/build/docs/build-config-file-schema

**Comment by lucemia** [comment]
> > > （requirements.txt 裡的 package 也會安裝 pytorch dependency，但是無法選擇 pytorch cuda version，會自動安裝對應 cuda 10.2 的 pytorch，所以設定成 requirements.txt 之後再重新安裝 pytorch）
> > 
> > 
> > 無法選擇 pytorch 的意思指的是什麼呢? requirements.txt 裡面是可以指定 version 的 https://github.com/livingbio/gstudio/blob/master/requirements/test.txt
> 
> requirments.txt 裡面其實沒有 torch, torchvision, torchaudio，是裡面某個 package 的 dependency 自動安裝 torch 的，不確定為什麼 pip 沒有自動抓對應系統 cuda 的 torch 安裝
> 
> 我嘗試修改 requirements.txt 看看

應該設定一個 requirements.in 然後透過 pip-compile 產出 requirements.txt
https://github.com/jazzband/pip-tools

**Comment by lucemia** [comment]
https://hub.docker.com/r/pytorch/pytorch/tags 可以改用這些有裝好 pytorch 的 image

**Comment by lucemia** [comment]
> 這裡提到可能�是硬碟不夠大 https://stackoverflow.com/questions/62669720/process-got-killed-when-building-docker-image-on-gcp
> 
> 預設是 100gb https://cloud.google.com/build/docs/build-config-file-schema

改了 200mb 沒有用

**Comment by achen353** [comment]
> https://hub.docker.com/r/pytorch/pytorch/tags 可以改用這些有裝好 pytorch 的 image

之前準備 deployment 時有嘗試用 pytorch 現成的 image，當時 pytorch version 和 conda 似乎在編譯這部分 third party 模型時會出問題
https://github.com/livingbio/fewshot-vid2vid/blob/d82c87aced50afd44fd162491ba5b59056b74034/scripts/install.sh#L36-L47

我再在 local 測試看看

**Comment by achen353** [comment]
# Final Solution
加入 pip flag `--no-cache-dir`：https://github.com/livingbio/fewshot-vid2vid/pull/3/commits/0e3384e18f921deb20cffac4a19ea8fc86c0d692

# 原因
似乎是在 GCP 上 pip install 太大的 package 就會 processed killed，解法參考：https://stackoverflow.com/a/69204294/11526586
